# Generated by Django 4.1.2 on 2022-10-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='institution_number',
            new_name='inst_num',
        ),
        migrations.AlterField(
            model_name='branch',
            name='capacity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
