# Generated by Django 4.1.2 on 2022-10-30 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banks', '0002_rename_institution_number_bank_inst_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to=settings.AUTH_USER_MODEL),
        ),
    ]
