# Generated by Django 4.1.2 on 2022-10-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_alter_bank_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='branches',
            field=models.ManyToManyField(to='banks.branch'),
        ),
    ]
