# Generated by Django 4.1.2 on 2022-10-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0009_alter_branch_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(default='admin@utoronto.ca', max_length=254, verbose_name='Email Address'),
        ),
    ]
